services:
  nestjs:
    build: .
    container_name: nestjs_app
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    user: "1000:1000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  postgres_data:
